// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAutocomplete: typeof import('element-ui/lib/autocomplete')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCheckbox: typeof import('element-ui/lib/checkbox')['default']
    ElCheckboxButton: typeof import('element-ui/lib/checkbox-button')['default']
    ElCheckboxGroup: typeof import('element-ui/lib/checkbox-group')['default']
    ElDatePicker: typeof import('element-ui/lib/date-picker')['default']
    ElEmpty: typeof import('element-ui/lib/empty')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElInputNumber: typeof import('element-ui/lib/input-number')['default']
    ElLink: typeof import('element-ui/lib/link')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElOptionGroup: typeof import('element-ui/lib/option-group')['default']
    ElRadio: typeof import('element-ui/lib/radio')['default']
    ElRadioButton: typeof import('element-ui/lib/radio-button')['default']
    ElRadioGroup: typeof import('element-ui/lib/radio-group')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElSwitch: typeof import('element-ui/lib/switch')['default']
    ElTag: typeof import('element-ui/lib/tag')['default']
    ElTimePicker: typeof import('element-ui/lib/time-picker')['default']
    KlChannelSearchbar: typeof import('./../packages')['ChannelSearchbar']
    KlDrawer: typeof import('./../packages')['Drawer']
    KlFormItem: typeof import('./../packages')['FormItem']
    KlLoginForm: typeof import('./../packages')['LoginForm']
    KlQrcode: typeof import('./../packages')['Qrcode']
    KlSidebar: typeof import('./../packages')['Sidebar']
    KlSidebarItem: typeof import('./../packages')['SidebarItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
