// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAutocomplete: typeof import('element-ui/lib/autocomplete')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ErrorPage: typeof import('./src/components/error-page.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Layout: typeof import('./src/components/layout.vue')['default']
    Main: typeof import('./src/components/main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
  }
}

export {}
